### ISSUE TITLE
CPU from beam going crazy

### ISSUE THREAD

**Issue by theworkerant** [smeevil/linter-elixir-credo#14]
I'm getting large spikes in CPU on the `beam` process that go away when I disable the plugin. It seems either the Linter or this repo is pretty aggressive on checking changes for violations. Anything to be done about this?

**Comment by Arcanemagus** [comment]
It looks like this linter provider specifies support for linting code on the fly (as you are editing the file). You can either disable this option entirely in the `Linter` package's settings, or you might try bumping up the delay for how long it waits before triggering a lint. I personally use 1500 ms instead of the default 300 ms.

**Comment by theworkerant** [comment]
@Arcanemagus Ah yea, good catch. Thanks, that should do the trick.
